server:
  port: 80

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm50373
    password: 031005
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
      show-sql: false