spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm552184
    password: 270605
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
      show-sql: true